#!/usr/bin/env bash
set -euxo pipefail

BENCH="scripts/bench"

# Set CLEAN=true to enable `lake clean`, false to disable
CLEAN=${CLEAN:-true}

# Prepare build
# Use build cache for proofwidgets, but not for anything else.
if [ "$CLEAN" = "true" ]; then
  lake clean
  # We sometimes see lingering locks. Maybe an NFS issue?
  rm -rf delme
  mv .lake delme
else
  echo "Skipping 'lake clean' (CLEAN=$CLEAN)"
fi

if [[ -f "measurements.jsonl" ]]; then
    mv "measurements.jsonl" "measurement.jsonl~"
fi

LEAN_PATH=$(lean --print-libdir) lake build proofwidgets
rm -f .lake/packages/batteries/.lake/build/bin/runLinter

# Run build
LAKE_OVERRIDE_LEAN=true LEAN=$(realpath "$BENCH/thp-build/fake-root/bin/lean") \
  "$BENCH/thp-build/measure-thp.py" -t build \
  -m instructions -m maxrss -m task-clock -m wall-clock -- \
  lakeprof record lake build --no-cache

python3 "$BENCH/thp-build/rename-json.py"

## Analyze lakeprof data
#lakeprof report -pj | jq -c '{metric: "build/lakeprof/longest build path//wall-clock", value: .[-1][2], unit: "s"}' >> measurements.jsonl
#lakeprof report -rj | jq -c '{metric: "build/lakeprof/longest rebuild path//wall-clock", value: .[-1][2], unit: "s"}' >> measurements.jsonl
#
## Upload lakeprof report
## Guarded to prevent accidental uploads (which wouldn't work anyways) during local runs.
#if [ -f build_upload_lakeprof_report ]; then
#  python3 "$BENCH/build/lakeprof_report_upload.py"
#fi
